### ISSUE TITLE
kubectl get pods --show-all has been deprecated

### ISSUE THREAD

**Issue by dogzzdogzz** [zxcvbnius/k8s-30-day-sharing#1]
In day 5 tutorial, kubectl get pods --show-all is introduced, however, 
Flag --show-all has been deprecated, will be removed in an upcoming release

Show all is the default now, -a is not required

**Comment by zxcvbnius** [comment]
Before version 1.10 we still need `-a` to display pods with the terminal state, I think it would be better to add a commit for this part. I will update Day 5 tutorial as soon as possible.
